[daphne]
accept = 443
connect = 0.0.0.0:8000
cert = /Users/admin/Downloads/campus/lib/python3.11/site-packages/sslserver/certs/development.crt
key = /Users/admin/Downloads/campus/lib/python3.11/site-packages/sslserver/certs/development.key
