CATEGORY_OPTIONS = (
    ('ONLINE_SERVICES', 'ONLINE_SERVICE'),
    ('TRAVEL', 'TRAVEL'),
    ('SALARY', 'SALARY'),
    ('RENT', 'RENT'),
    ('OTHERS', 'OTHERS'),
  )

APPROVAL_STATUSES = (
    ('PENDING', 'PENDING'),
    ('APPROVED', 'APPROVED'),
    ('REJECTED', 'REJECTED'),
  )
DELETE_STATUSES= (
    ('ACTIVE', 'ACTIVE'),
    ('DELETED', 'DELETED'),
  )
