# Generated by Django 5.0.6 on 2024-09-01 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_participant_anonymous_user_id_alter_participant_user'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('L', 'Like'), ('F', 'Follow'), ('UL', 'Unlike'), ('UF', 'Unfollow')], max_length=2),
        ),
        migrations.AlterField(
            model_name='activity',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='object_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='activity',
            unique_together={('user', 'content_type', 'object_id', 'activity_type')},
        ),
    ]
