# Generated by Django 5.0.6 on 2024-09-04 15:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_rename_timestamp_activity_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.UniqueConstraint(fields=('anonymous_user_id', 'room'), name='unique_anonymous_user_in_room'),
        ),
    ]
