# Generated by Django 5.0.6 on 2024-09-18 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0005_participant_unique_anonymous_user_in_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='duration',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='room',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
