# Generated by Django 5.0.6 on 2024-10-01 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0007_calendarevent_attendee'),
        ('feed', '0014_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='visibility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.visibility'),
        ),
    ]
