# Generated by Django 5.0.6 on 2024-09-08 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_reset_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='deleted_status',
            field=models.BooleanField(default=False),
        ),
    ]
