# Generated by Django 5.0.6 on 2024-10-04 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_deleted_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='recovery_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
