# Generated by Django 3.2 on 2024-07-11 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_auto_20240709_1929'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usertopic',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='usertopic',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='usertopic',
            name='user',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='follower_count',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.DeleteModel(
            name='UserTopic',
        ),
    ]
