# Generated by Django 3.2 on 2024-07-15 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_postfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postfile',
            name='file',
        ),
        migrations.AddField(
            model_name='postfile',
            name='attachment',
            field=models.FileField(null=True, upload_to='post_files/'),
        ),
    ]
