# Generated by Django 3.2 on 2024-07-15 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_auto_20240715_1858'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostFile',
            new_name='PostAttachment',
        ),
    ]
