# Generated by Django 5.0.6 on 2024-09-01 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0010_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postattachment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='feed.post'),
        ),
    ]
