# Generated by Django 5.0.6 on 2024-09-07 13:12

import bluecampus.app.feed.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0011_alter_postattachment_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterModelOptions(
            name='postattachment',
            options={'verbose_name': 'Post Attachment', 'verbose_name_plural': 'Post Attachments'},
        ),
        migrations.AlterField(
            model_name='post',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='feed.topic'),
        ),
        migrations.AlterField(
            model_name='postattachment',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=bluecampus.app.feed.models.upload_to),
        ),
    ]
