# Generated by Django 5.0.6 on 2024-10-04 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0014_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_class_start', models.BooleanField(default=True)),
                ('email_new_follower', models.BooleanField(default=True)),
                ('email_new_badge', models.BooleanField(default=True)),
                ('push_class_start', models.BooleanField(default=True)),
                ('push_new_follower', models.BooleanField(default=True)),
                ('push_new_badge', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
