# Generated by Django 5.0.6 on 2024-10-06 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0015_notificationsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postattachment',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='post_upload/'),
        ),
    ]
